name: Check JSON schema

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Update schemas
        run: npm run update-schemas

      - name: Run prettier
        run: .github/bin/check-for-schema-changes
